<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Member;
use Carbon\Carbon;

class MemberSeeder extends Seeder
{
    public function run(): void
    {
        $members = [
            [
                'first_name' => 'Juan',
                'last_name' => 'Pérez',
                'dni' => '30123456',
                'birth_date' => '1990-05-14',
                'address' => 'Av. Corrientes 1234',
                'phone' => '1123456789',
                'email' => 'juan.perez@example.com',
                'observations' => 'Miembro activo desde 2022. Participa en clases de spinning.',
                'status' => 'activo',
                'joined_at' => '2022-01-10',
                'membership_expires_at' => '2025-12-31',
            ],
            [
                'first_name' => 'María',
                'last_name' => 'González',
                'dni' => '28999888',
                'birth_date' => '1988-03-22',
                'address' => 'San Martín 550',
                'phone' => '1134567890',
                'email' => 'maria.gonzalez@example.com',
                'observations' => 'Prefiere entrenar por la mañana.',
                'status' => 'activo',
                'joined_at' => '2023-05-12',
                'membership_expires_at' => '2026-05-12',
            ],
            [
                'first_name' => 'Carlos',
                'last_name' => 'Fernández',
                'dni' => '31555999',
                'birth_date' => '1995-07-09',
                'address' => 'Rivadavia 8000',
                'phone' => '1167894321',
                'email' => 'carlos.fernandez@example.com',
                'observations' => 'Suspendido temporalmente por falta de pago.',
                'status' => 'suspendido',
                'joined_at' => '2021-09-01',
                'membership_expires_at' => '2025-09-01',
            ],
            [
                'first_name' => 'Laura',
                'last_name' => 'Torres',
                'dni' => '33456789',
                'birth_date' => '1992-10-10',
                'address' => 'Av. Belgrano 1500',
                'phone' => '1176543210',
                'email' => 'laura.torres@example.com',
                'observations' => null,
                'status' => 'activo',
                'joined_at' => '2022-11-15',
                'membership_expires_at' => '2026-11-15',
            ],
            [
                'first_name' => 'Diego',
                'last_name' => 'Ramírez',
                'dni' => '29888888',
                'birth_date' => '1987-01-05',
                'address' => 'Mitre 2330',
                'phone' => '1187654321',
                'email' => 'diego.ramirez@example.com',
                'observations' => 'Entrenamiento personalizado 3 veces por semana.',
                'status' => 'activo',
                'joined_at' => '2023-04-01',
                'membership_expires_at' => '2026-04-01',
            ],
            [
                'first_name' => 'Lucía',
                'last_name' => 'Martínez',
                'dni' => '31222333',
                'birth_date' => '1998-09-18',
                'address' => 'Calle 9 N°120',
                'phone' => '1198765432',
                'email' => 'lucia.martinez@example.com',
                'observations' => 'Miembro inactivo desde julio 2024.',
                'status' => 'inactivo',
                'joined_at' => '2020-06-10',
                'membership_expires_at' => '2024-06-10',
            ],
            [
                'first_name' => 'Fernando',
                'last_name' => 'Suárez',
                'dni' => '32222111',
                'birth_date' => '1991-12-02',
                'address' => 'Av. Cabildo 2500',
                'phone' => '1101122233',
                'email' => 'fernando.suarez@example.com',
                'observations' => 'Se destaca en musculación.',
                'status' => 'activo',
                'joined_at' => '2022-08-18',
                'membership_expires_at' => '2025-08-18',
            ],
            [
                'first_name' => 'Valeria',
                'last_name' => 'Castro',
                'dni' => '27666555',
                'birth_date' => '1985-06-30',
                'address' => 'Roca 180',
                'phone' => '1144445555',
                'email' => 'valeria.castro@example.com',
                'observations' => null,
                'status' => 'activo',
                'joined_at' => '2021-12-20',
                'membership_expires_at' => '2025-12-20',
            ],
            [
                'first_name' => 'Andrés',
                'last_name' => 'Molina',
                'dni' => '30333333',
                'birth_date' => '1990-11-11',
                'address' => '9 de Julio 999',
                'phone' => '1177778888',
                'email' => 'andres.molina@example.com',
                'observations' => 'Prefiere horario nocturno.',
                'status' => 'activo',
                'joined_at' => '2023-03-15',
                'membership_expires_at' => '2026-03-15',
            ],
            [
                'first_name' => 'Paula',
                'last_name' => 'Rojas',
                'dni' => '29900123',
                'birth_date' => '1996-02-25',
                'address' => 'Hipólito Yrigoyen 4550',
                'phone' => '1122233344',
                'email' => 'paula.rojas@example.com',
                'observations' => 'Ha participado en torneos internos.',
                'status' => 'activo',
                'joined_at' => '2021-07-01',
                'membership_expires_at' => '2025-07-01',
            ],
            [
                'first_name' => 'Ricardo',
                'last_name' => 'Domínguez',
                'dni' => '27889900',
                'birth_date' => '1983-08-05',
                'address' => 'Catamarca 1220',
                'phone' => '1100099988',
                'email' => 'ricardo.dominguez@example.com',
                'observations' => 'Suspendido temporalmente por lesión.',
                'status' => 'suspendido',
                'joined_at' => '2022-10-10',
                'membership_expires_at' => '2025-10-10',
            ],
            [
                'first_name' => 'Ana',
                'last_name' => 'Sánchez',
                'dni' => '30111999',
                'birth_date' => '1994-04-04',
                'address' => 'Av. La Plata 330',
                'phone' => '1133344455',
                'email' => 'ana.sanchez@example.com',
                'observations' => 'Miembro nueva, sin historial médico aún.',
                'status' => 'activo',
                'joined_at' => now(),
                'membership_expires_at' => Carbon::now()->addYear(),
            ],
        ];

        foreach ($members as $data) {
            Member::create($data);
        }
    }
}
